name: Awesome Venezuela Update

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run script
        run: uv run --with google-genai --with requests --with beautifulsoup4 scrape.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'gh-actions: ${{ steps.date.outputs.date }} update'
          add: 'README.md'
